a=input("Enter the first number=")
b=input("Enter the second number=")
a=int(a)
b=int(b)
print("addition =",a+b)
print("subtraction =",a-b)
print("multiplication =",a*b)
print("division =",a/b)